
# Libraries
all:
#				mkdir ../lib
				$(MAKE) -C adtl
				$(MAKE) -C ccl
				$(MAKE) -C sysl
				$(MAKE) -C iol
				$(MAKE) -C mathl
				$(MAKE) -C miscl
				$(MAKE) -C netl
				$(MAKE) -C nshl
				$(MAKE) -C nspcl
clean:
				$(MAKE) -C adtl clean
				$(MAKE) -C ccl clean
				$(MAKE) -C sysl clean
				$(MAKE) -C iol clean
				$(MAKE) -C mathl clean
				$(MAKE) -C miscl clean
				$(MAKE) -C netl clean
				$(MAKE) -C nshl clean
				$(MAKE) -C nspcl clean

install:		all
				echo Static libraries
