
# Libraries 
all:
				$(MAKE) -C adtn
				$(MAKE) -C ion 
				$(MAKE) -C mathn
				$(MAKE) -C median
				$(MAKE) -C miscn 
				$(MAKE) -C netn 
				$(MAKE) -C nspcn
				$(MAKE) -C sysn
clean:
				$(MAKE) -C adtn clean
				$(MAKE) -C ion clean
				$(MAKE) -C mathn clean
				$(MAKE) -C median clean
				$(MAKE) -C miscn clean
				$(MAKE) -C netn clean
				$(MAKE) -C nspcn clean
				$(MAKE) -C sysn clean

install:		all
				echo Static libraries
